// Map<String, Map<String, String>>
var translationKey = {
  'en_US': {
    'Upload File': 'Upload File',
    'Media Player': 'Media Player',
    'Flutter Downloader': 'Flutter Downloader',
    'Switch Language': 'Switch Language',
    'File : 1': 'File : 1',
    'File : 2': 'File : 2',
    'File : 3': 'File : 3',
    'File : 4': 'File : 4',
    'File : 5': 'File : 5',
    'File : 6': 'File : 6',
    'File : 7': 'File : 7',
    'File : 8': 'File : 8',
    'File : 9': 'File : 9',
    'File : 10': 'File : 10',
  },
  'pt_BR': {
    'Upload File': 'Subir arquivo',
    'Media Player': 'Reprodutor de mídia',
    'Flutter Downloader': 'Flutter Downloader',
    'Switch Language': 'Mudar de idioma',
    'File : 1': 'Arquivo : 1',
    'File : 2': 'Arquivo : 2',
    'File : 3': 'Arquivo : 3',
    'File : 4': 'Arquivo : 4',
    'File : 5': 'Arquivo : 5',
    'File : 6': 'Arquivo : 6',
    'File : 7': 'Arquivo : 7',
    'File : 8': 'Arquivo : 8',
    'File : 9': 'Arquivo : 9',
    'File : 10': 'Arquivo : 10',
  },
  'ar': {
    'Upload File': 'رفع ملف',
    'Media Player': 'مشغل وسائط',
    'Flutter Downloader': 'رفرفة تنزيل',
    'Switch Language': 'تبديل اللغة',
    'File : 1': 'ملف: 1',
    'File : 2': 'ملف : 2',
    'File : 3': 'ملف : 3',
    'File : 4': 'ملف : 4',
    'File : 5': 'ملف : 5',
    'File : 6': 'ملف : 6',
    'File : 7': 'ملف : 7',
    'File : 8': 'ملف : 8',
    'File : 9': 'ملف : 9',
    'File : 10': 'ملف : 10',

  },
};
